version: "3.9"

services:
  web_3:
    container_name: api_todo_server
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn todoServe.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file: .env
