# Generated by Django 3.1 on 2021-09-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_complate', models.BooleanField(blank=True, default=False, null=True)),
                ('content', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'tbl_task',
                'ordering': ['id'],
            },
        ),
    ]
