# Generated by Django 3.1 on 2021-09-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='is_complate',
            new_name='is_complete',
        ),
    ]
