# Account type
ACCOUNT_TYPE_GOOGLE = 1
ACCOUNT_TYPE_FACEBOOK = 2
ACCOUNT_TYPE_NORMAL = 0

ACCOUNT_TYPE = (
    (ACCOUNT_TYPE_GOOGLE, ACCOUNT_TYPE_FACEBOOK),
    (ACCOUNT_TYPE_FACEBOOK, ACCOUNT_TYPE_NORMAL),
    (ACCOUNT_TYPE_NORMAL, ACCOUNT_TYPE_GOOGLE),
)

# Type of course
COURSE_BACK_END = 0
COURSE_FONT_END = 1
COURSE_JAVASCRIPT = 2
COURSE_REACT = 3
COURSE_VUE = 4
COURSE_ANGULAR = 5
COURSE_HTML = 6
COURSE_CSS = 7
COURSE_PYTHON = 8
COURSE_DOT_NET = 9
COURSE_JAVA = 10
COURSE_DO_HOA = 11
COURSE_NODEJS = 12
COURSE_WORLDPRESS = 13
COURSE_PHP = 14
COURSE_DJANGO = 15
COURSE_DESIGN = 16
COURSE_PHOTOSHOP = 17
COURSE_REACT_NATIVE = 18
COURSE_ANDROI = 19
COURSE_IOS = 20
COURSE_FLUTER = 21
COURSE_SCSS = 22
COURSE_BOOTSTRAP = 23
COURSE_MYSQL = 24
COURSE_JQUERY = 25
COURSE_TYPECRIPT = 26
COURSE_GIT = 27
COURSE_REDUX = 28
COURSE_MONGODB = 29
COURSE_POSTGRESQL = 30
COURSE_NEXTJS = 31
COURSE_AWS = 32
COURSE_OTHER = 33

COURSE_TYPE_OPTION = (
    (COURSE_BACK_END, COURSE_BACK_END),
    (COURSE_FONT_END, COURSE_FONT_END),
    (COURSE_JAVASCRIPT, COURSE_JAVASCRIPT),
    (COURSE_REACT, COURSE_REACT),
    (COURSE_VUE, COURSE_VUE),
    (COURSE_ANGULAR, COURSE_ANGULAR),
    (COURSE_HTML, COURSE_HTML),
    (COURSE_CSS, COURSE_CSS),
    (COURSE_PYTHON, COURSE_PYTHON),
    (COURSE_DOT_NET, COURSE_DOT_NET),
    (COURSE_JAVA, COURSE_JAVA),
    (COURSE_DO_HOA, COURSE_DO_HOA),
    (COURSE_NODEJS, COURSE_NODEJS),
    (COURSE_WORLDPRESS, COURSE_WORLDPRESS),
    (COURSE_PHP, COURSE_PHP),
    (COURSE_DJANGO, COURSE_DJANGO),
    (COURSE_DESIGN, COURSE_DESIGN),
    (COURSE_PHOTOSHOP, COURSE_PHOTOSHOP),
    (COURSE_REACT_NATIVE, COURSE_REACT_NATIVE),
    (COURSE_ANDROI, COURSE_ANDROI),
    (COURSE_IOS, COURSE_IOS),
    (COURSE_BOOTSTRAP, COURSE_BOOTSTRAP),
    (COURSE_SCSS, COURSE_SCSS),
    (COURSE_FLUTER, COURSE_FLUTER),
    (COURSE_JQUERY, COURSE_JQUERY),
    (COURSE_MYSQL, COURSE_MYSQL),
    (COURSE_TYPECRIPT, COURSE_TYPECRIPT),
    (COURSE_GIT, COURSE_GIT),
    (COURSE_REDUX, COURSE_REDUX),
    (COURSE_MONGODB, COURSE_MONGODB),
    (COURSE_POSTGRESQL, COURSE_POSTGRESQL),
    (COURSE_AWS, COURSE_AWS),
    (COURSE_NEXTJS, COURSE_NEXTJS),
    (COURSE_OTHER, COURSE_OTHER),
)

# Type of course
STATUS_COURSE_IS_NEW = 0
STATUS_COURSE_IS_ACTIVE = 1
STATUS_COURSE_IS_WAITING = 2
STATUS_COURSE_IS_FAILED = 3

STATUS_COURSE_OPTION = (
    (STATUS_COURSE_IS_NEW, STATUS_COURSE_IS_NEW),
    (STATUS_COURSE_IS_ACTIVE, STATUS_COURSE_IS_ACTIVE),
    (STATUS_COURSE_IS_WAITING, STATUS_COURSE_IS_WAITING),
    (STATUS_COURSE_IS_FAILED, STATUS_COURSE_IS_FAILED),
)

# Type of Photo
PHOTO_TYPE_USER = 2
PHOTO_TYPE_COURSE = 1
PHOTO_TYPE_OTHER = 0

PHOTO_TYPE_OPTION = (
    (PHOTO_TYPE_OTHER, PHOTO_TYPE_OTHER),
    (PHOTO_TYPE_COURSE, PHOTO_TYPE_COURSE),
    (PHOTO_TYPE_USER, PHOTO_TYPE_USER),
)

# Type of Position
USER_ADMIN = 0
USER_LECTURERS = 1
USER_STUDENT = 2

USER_POSITION_TYPE_OPTION = (
    (USER_ADMIN, USER_ADMIN),
    (USER_LECTURERS, USER_LECTURERS),
    (USER_STUDENT, USER_STUDENT),
)
